### ISSUE TITLE
unsuccessful installation under Symfony 5.4 with PHP 8.0

### ISSUE THREAD

**Issue by velkony** [PayU-EMEA/openpayu_php#123]
HI, 
when trying to install the package
composer require openpayu/openpayu
I get the following error:

PHP Warning:  PHP Startup: ^(text/|application/xhtml\+xml) (offset=0): unrecognised compile-time option bit(s) in Unknown on line 0
PHP Fatal error:  Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:137

Does anyone have any idea where the problem is?

**Comment by drealecs** [comment]
That is an error in composer phar itself.
The phar build comes with a very old symfony console version, probably so that it can be used on any php versions: https://github.com/composer/composer/blob/main/composer.lock#L658-L659
Issue was discussed recently here: https://twitter.com/seldaek/status/1461670175976169478

The workaround suggested here https://github.com/composer/composer/issues/7836 is to disable pcre jit.
I think you can do this with: `php -d pcre.jit=0 <path-to-composer.phar> require openpayu/openpayu`.
I'm not sure if that will help but please try it and let us know, if possible.

**Comment by velkony** [comment]
Thanks for your reply.
I tested the solution that you suggested but unfortunately it doesn't work.
I also made a change directly in the php.ini
Do you have any other suggestions?

**Comment by velkony** [comment]
I solved the problem with upgrade
sudo apt update
sudo apt upgrade

**Comment by drealecs** [comment]
Happy to hear that you managed to solve the issue.
Can you list here the updated packages that might be relevant to fixing the issue? Was it PHP itself?

**Comment by velkony** [comment]
Do you have any prepared bundle or service for Symfony, something like https://github.com/Darneus/payu for Nette?
